---
- hosts: all
  become: true
  vars:
    doc_root: /var/www/website
  tasks:
    - name: Create directory
      file: path={{ doc_root }} state=directory owner=www-data group=www-data

    - name: Set up HTML file
      copy: src=index.html dest={{ doc_root }}/index.html owner=www-data group=www-data mode=0644
