--- 
- 
  hosts: all
  tasks:
    -  
      name: "Update all packages to their latest version"
      apt: 
        state: latest
        name: "python3"
    - name: root python fix
      lineinfile:
        path: /root/.bashrc
        line: 'alias python=python3'
        insertbefore: BOF
    - name: jim python fix
      lineinfile:
        path: /jim/.bashrc
        line: 'alias python=python3'
        insertbefore: BOF
