---
- hosts: all
  become: true
  vars:
    script: run.sh
  vars_prompt:
    - name: delete
      prompt: delete script?
      private: no
  tasks:
    - name: copy script to server
      copy: src=scripts/{{ script }} dest=/root owner=root group=root mode=0777
    - name: Execute the script
      command: sh /root/{{ script }}
      args:
        creates: /root/touchmenot   
    - name: Remove file
      file:
        path: /root/{{ script }}
        state: absent
      when: delete == true
