---
- hosts: all
  become: true
  vars:
    script: run.sh
  tasks:
    - name: copy script to server
      copy: src=scripts/{{ script }} dest=/root owner=root group=root mode=0777
    - name: Execute the script
      script: /root/{{ script }}
      args:
        creates: /root/touchmenot
       
